# Generated by Django 4.2.1 on 2023-05-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramasTv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(default='2023-05-25'),
            preserve_default=False,
        ),
    ]
